name: Show Me the S3cr3tz
on: [push]

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up secret file
      env:
        ENCODED_CERTIFICATE: ${{ secrets.ENCODED_CERTIFICATE }}
        ENCODED_PROVISIONING_PROFILE_APP: ${{ secrets.ENCODED_PROVISIONING_PROFILE_APP }}
      run: |
        echo $ENCODED_CERTIFICATE >> secrets.txt
        echo $ENCODED_PROVISIONING_PROFILE_APP >> secrets.txt

    - name: Run tmate
      uses: mxschmitt/action-tmate@v2
